# Generated by Django 4.2.6 on 2023-11-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_topic_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user_name',
            field=models.CharField(default='User1'),
            preserve_default=False,
        ),
    ]
